### PR TITLE
fix: fixed vehicles not being cleaned up properly

### LINKED ISSUE #44: Spawned vehicles don't get cleaned up properly
Invoking /spawncars can result in cars spawning on top of each other. Additionally, vehicles don't always spawn fully, and it takes several invocations of the command to warm up the streaming system as if the model requests are not awaited correctly.

The cleanup issue can be reproduced by either:
- moving far enough away from spawn, then returning and attempting to spawn cars, or 
- more reliably by having two players on the server, and having client A spawn cars first, followed by client B.
  - cars will be cleaned up correctly if they were spawned on the same client

### PR DESCRIPTION
**Pull request by tomezpl**
This PR fixes a bug where spawning vehicles would not clean up the previously spawned set, causing them to spawn on top of each other.

Closes #44

### CODE REVIEW

File: src/SurviveTheHuntClient/Helpers/SyncedVehicle.cs [hunk 1]
```diff
@@ -0,0 +1,43 @@
+﻿using CitizenFX.Core;
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace SurviveTheHuntClient.Helpers
+{
+    public class SyncedVehicle
```
Comment (tomezpl) [inline src/SurviveTheHuntClient/Helpers/SyncedVehicle.cs:10]: summary

File: src/SurviveTheHuntClient/MainScript.cs [hunk 2]
```diff
@@ -36,7 +36,17 @@ public class MainScript : ClientScript
         /// Vehicles spawned by the gamemode at the spawn area. This is used to delete vehicles on the next <see cref="SpawnCars"/> call.
         /// </summary>
         /// <remarks>TODO: Move this to server-side so any player can spawn vehicles with the previous batch deleting properly?</remarks>
```
Comment (tomezpl) [inline src/SurviveTheHuntClient/MainScript.cs:38]: smell ya later todo

File: src/SurviveTheHuntClient/MainScript.cs [hunk 3]
```diff
@@ -120,7 +134,10 @@ private void OnClientResourceStart(string resource)
 
                 RegisterCommand("spawncars", new Action(() =>
                 {
-                    SpawnCars();
+                    if (!IsSpawningCars)
```
Comment (tomezpl) [inline src/SurviveTheHuntClient/MainScript.cs:137]: leave a comment why we're not spawning instantly
